export const charactersInfo = [
  "Luke Skywalker, a Force-sensitive human male, was a legendary Jedi Master who fought in the Galactic Civil War during the reign of the Galactic Empire. Along with his companions, Princess Leia Organa and General Han Solo, Skywalker served as a revolutionary on the side of the Alliance to Restore the Republic—an organization committed to the downfall of the Galactic Empire and the restoration of democracy. Following the war, Skywalker became a living legend, and was remembered as one of the greatest Jedi in galactic history.",
  "C-3PO (See-Threepio) was a 3PO-series protocol droid designed to interact with organics, programmed primarily for etiquette and protocol. Sometimes referred to as Threepio, he was fluent in over six million forms of communication, and developed a fussy and worry-prone personality throughout his many decades of operation. Along with his counterpart, the astromech droid R2-D2, C-3PO constantly found himself directly involved in pivotal moments of galactic history, and aided in saving the galaxy on many occasions.",
  "R2-D2, pronounced Artoo-Detoo and often referred to as R2 (Artoo), was an R2-series astromech droid manufactured by Industrial Automaton with masculine programming. A smart, spunky droid who would serve a multitude of masters over his lifetime, R2-D2 was never given a full memory wipe nor did he ever receive new programming, with these factors resulting in an adventurous and independent attitude. Often finding himself in pivotal moments in galactic history, his bravery and ingenuity saved the galaxy on numerous occasions.",
  "Anakin Skywalker was a Force-sensitive Human male who served the Galactic Republic as a Jedi Knight and later served the Galactic Empire as the Sith Lord Darth Vader. Born to the slave Shmi Skywalker in 41.9 BBY, Anakin was conceived by midi-chlorians, the symbiotic organisms that allowed individuals to touch the Force, and he and his mother were brought to the desert planet of Tatooine to be the slaves of Gardulla the Hutt. They soon ended up as the property of the Toydarian Watto, and Skywalker exhibited exceptional piloting skills and a reputation for being able to build and repair anything even at a young age. In 32 BBY, Skywalker encountered the Jedi Qui-Gon Jinn and Padmé Amidala, and he helped them secure the parts they needed for their starship by winning the Boonta Eve Classic podracing event—only to learn that he had also won his freedom in doing so.",
  "Leia Organa Solo (born Leia Amidala Skywalker), a Force-sensitive Human female was at various stages of her life, a politician, revolutionary, and Jedi Knight of the New Jedi Order. The daughter of Jedi Knight Anakin Skywalker and Senator Padmé Amidala of Naboo, Leia was the younger twin sister of Luke Skywalker, and, shortly after her birth, she became the adopted daughter of Bail Organa and Queen Breha of Alderaan, making her a Princess of Alderaan. An accomplished Senator, Leia Organa was most famous for her strong leadership during the Galactic Civil War and other subsequent galactic conflicts, making her one of the galaxy's greatest heroes. Later she married Han Solo, and became the mother of their three children: Jaina, Jacen, and Anakin Solo. Around the start of the Swarm War, Leia unknowingly became a grandmother through Jacen's daughter Allana.",
  "Owen Lars was the son of moisture farmer Cliegg Lars and the stepbrother of Anakin Skywalker. He married Beru Whitesun, and after his father's death, inherited his moisture farm. In 19 BBY, Beru convinced Owen to adopt Anakin's son, Luke Skywalker, as Anakin had turned to the dark side and become the infamous Darth Vader.",
  "Beru Whitesun Lars, the wife of Owen Lars, was a Tatooinian woman who raised Luke Skywalker after the fall of the Galactic Republic. Coming from a long line of moisture farmers, Beru Whitesun grew up near Mos Eisley on Tatooine. On a trip to Anchorhead, she met Owen Lars, the son of another moisture farmer, Cliegg Lars. Beru and Owen fell in love, and Beru later became part of the Lars family.",
  "R5-D4, also referred to as R5 (Arfive) and called \"Red\" by Luke Skywalker, was a red and white-striped R5 astromech droid owned by a group of Jawas on Tatooine in the early days of the Galactic Civil War. Shortly before the Battle of Yavin, the Jawas attempted to sell him to Owen Lars, but the droid purposely malfunctioned his motivator at the advice of R2-D2, so that Lars could purchase R2-D2 in R5-D4's place. The droid survived an Imperial attack on the sandcrawler soon after, and went out to find the Rebellion. R5 was still active by the time of the New Republic Era, and eventually came into the service of Mos Eisley hangar manager Peli Motto. He was later sold to the Mandalorian Din Djarin for his mission to the Living Waters of Mandalore.",
  "Biggs Darklighter was a human male ace pilot who fought for the Alliance to Restore the Republic during the early days of the Galactic Civil War. He grew up on the desert world of Tatooine, where he became a close boyhood friend of Luke Skywalker. The two became pilots and dreamed of leaving Tatooine. Darklighter left his homeworld for the Imperial Academy, but defected from the Galactic Empire after graduation in order to join the Rebel Alliance. He returned to Tatooine one final time to tell Skywalker of his plans.",
  "Obi-Wan Kenobi was a legendary Force-sensitive human male Jedi Master who served on the Jedi High Council during the final years of the Republic Era. As a High Jedi General, Kenobi served in the Grand Army of the Republic that fought against the Separatist Droid Army during the Clone Wars, and was nicknamed \"the Negotiator.\" Kenobi, however, was forced into exile as a result of the Great Jedi Purge initiated by the Republic's own clone troopers when Republic Supreme Chancellor, secretly Darth Sidious, implemented Order 66. As a mentor, Kenobi was responsible for training two members of the Skywalker family, Anakin and Luke Skywalker, both of whom served in turn as his Padawan in the ways of the Force."] 

export const planetsInfo = [
  "Tatooine was a sparsely inhabited circumbinary desert planet located in the galaxy's Outer Rim Territories. Part of a binary star system, the planet orbited two scorching suns, resulting in the world lacking the necessary surface water to sustain large populations. As a result, many residents of the planet instead drew water from the atmosphere via moisture farms. The planet also had little surface vegetation. It was the homeworld to the native Jawa and Tusken Raider species and of Anakin and Luke Skywalker, who would go on to shape galactic history.",
  "Alderaan, located in the Core Worlds, was a terrestrial planet covered with mountains. During the waning decades of the Galactic Republic, it was ruled by Queen Breha Organa and represented in the Galactic Senate by her husband, Senator Bail Prestor Organa. Alderaan was regarded for its natural beauty, its tranquility, and the sophistication of its arts and culture.",
  "Yavin IV was the jungle-covered fourth moon in orbit around the red gas giant Yavin Prime. Prior to and during the Galactic Civil War, it hosted the headquarters of the Alliance to Restore the Republic, a group of resistance fighters that opposed the dominant Galactic Empire.[2] Following a major battle that took place around Yavin,[9] the Alliance went on the run, and eventually relocated its headquarters to Hoth.",
  "Hoth was the sixth planet of the remote Hoth system. A desolate world covered with ice and snow, located in the Anoat sector, a rarely-traveled portion of the Outer Rim Territories, it became famous as the one-time location of the Alliance to Restore the Republic's Echo Base during the Galactic Civil War. The base was discovered by the Empire in 3 ABY, precipitating the Battle of Hoth, a major engagement during which the Rebels suffered heavy casualties and lost Echo Base.",
  "Dagobah was a remote, unexplored planet in the Dagobah system, and one of the purest places in the galaxy within the Force. A remote world of swamps and forests, it served as a refuge for Jedi Grand Master Yoda during his exile after the destruction of the Jedi Order. Luke Skywalker received advanced training in the ways of the Force under Jedi Master Yoda on Dagobah, and it was later the place of Yoda's death and transformation into the Force.",
  "Bespin was a gas giant in the star system of the same name in the Anoat sector, its riches manifested in the form of rare tibanna gas. Attracting mining interests and remaining unaffiliated in galactic affairs, Ugnaughts were employed to extract tibanna from repulsorlifted facilities whilst Bespin's mostly human population resided in the open upper levels, exposed to a thin layer of breathable atmosphere in an area known as a \"Life Zone.\"",
  "Endor, designated IX3244-A, also known as the Forest Moon of Endor or the Sanctuary Moon, was a small forested moon that was the ninth moon that orbited the Outer Rim planet of the same name. It was the homeworld of the sentient Dulok, Ewok, and Yuzzum species, as well as the Wistie and semi-sentient Gorax races.",
  "Naboo was a bountiful planet in the Chommell sector of the Mid Rim, in the Trailing Sectors and close to the border of the Outer Rim Territories. It was home to the indigenous Gungan species and to a population of humans known as the Naboo. Naboo was pushed to the forefront of galactic politics as the birthplace of the Dark Lord of the Sith Sheev Palpatine, who served as its representative in the Senate of the Galactic Republic.",
  "Coruscant (pronounced /'kɔɹəsɑnt/), also known as Jewel of the Core Worlds, or Imperial Center during the rule of the Galactic Empire, was an ecumenopolis—a city-covered planet, collectively known as Imperial City— in the Coruscant system of the Core Worlds. Though debated by historians, it was generally believed that Coruscant was the original homeworld of humanity. Coruscant was at one point also historically the home of the ancient Taung and Zhell. Noted for its cosmopolitan culture and towering skyscrapers, Coruscant's population consisted of trillions of citizens hailing from a vast array of both humanoid and alien species. In addition, Coruscant's strategic location at the end of several major trade routes enabled it to grow in power and influence, causing the city-planet to surpass its early rivals and become the hub of galactic culture, education, finance, fine arts, politics and technology. It was the location of several major landmarks, including the Jedi Temple, Monument Plaza, and the Senate Building.",
  "Kamino (pronounced /kə'minoʊ/) was an aquatic planet located in a remote star system in Wild Space of the galaxy. It was sometimes considered extragalactic due to being in close proximity to the Rishi Maze dwarf satellite galaxy. It was inhabited by the Kaminoans—a race of tall, elegant beings with long necks who were regarded as a mysterious species that tended to keep to themselves. They were also known for their cloning technology, which was used to create a clone army for the Galactic Republic."
]

export const vehiclesInfo = [
  "Sandcrawlers, originally called digger crawlers, were huge mobile fortresses used by the Jawas as their transport and shelter in the deserts of Tatooine and Arvala-7. They were equipped with a magnetic suction tube for sucking droids and scrap into the cargo hold. They also contained cargo holds, scrap-processing facilities, and quarters for crew and passengers. They were large enough to fit an entire Jawa clan.",
  "The X-34 was a civilian landspeeder of mundane design produced by SoroSuub Corporation. Built with a powerful repulsorlift engine augmented with three air-cooled thrust turbines, the X-34 hovered up to a meter off the ground during operation. The vehicles were capable of crossing rough terrain, and were well-suited for harsh desert climates. Owners could choose from either an open-air or sealed cockpit, although the speeders lacked any form of combat capability in the form of weapon mounts or armor. The X-34 was fast, if fairly nondescript in appearance, and measured 3.4 meters in length. X-34 landspeeders utilized by the Alliance to Restore the Republic were retrofitted with blaster cannons, such as the Mark II Medium Blaster.",
  "T-16 skyhoppers, also known as the T-16 airspeeders, were Skyhoppers, that were personal repulsorlift airspeeders manufactured by Incom Corporation, recognizable by its distinctive tri-wing design. It was a popular, high-performance airspeeder due to its stable and reliable transportation on almost any world, and thus provided many youths with their first flight training. The T-16's trihedral design greatly resembled that of the Imperial Lambda-class T-4a shuttle.",
  "The TIE/LN starfighter, or TIE/line starfighter, simply known as the TIE Fighter or T/F, was the standard Imperial starfighter seen in massive numbers throughout most of the Galactic Civil War and onward. Occasionally, due to their distinct shape, Rebel and New Republic pilots referred to the craft as \"eyeballs.\"",
  "The snowspeeder was a type of T-47 airspeeder manufactured by Incom Corporation and modified by the Rebel Alliance. When the Galactic Empire attacked Echo Base, snowspeeders saw use during the Battle of Hoth, where the T-47s attempted to take down the Empire's All Terrain Armored Transports with their tow cables",
  "ATAT300 was the callsign of an All Terrain Tactical Enforcer within the Grand Army of the Republic that was used by several clone troopers of Execute Battalion to board Cad Bane's Munificent-class star frigate during the Battle of Devaron.",
  "The TIE/sa bomber, formally known as the TIE Surface Assault Bomber and also known as the TIE/sa tactical bomber or simply the TIE bomber, was a bombing variant of the TIE fighter series used by the Galactic Empire. An evolution of the TIE/gt, the TIE bomber was their main source of anti-emplacement air-support. They were nicknamed \"dupes\" by the New Republic pilot Wyl Lark",
  "The AT-ST Raider was a warpainted and heavily modified variant of the All Terrain Scout Transport used by a Klatooinian raider tribe after the fall of the Galactic Empire. The AT-ST was later destroyed by Din Djarin and Cara Dune when they drew it to the village that had been raided regularly and it stepped in a man-made lake, rendering it useless. Djarin attached a grav charge to the wrecked walker and blew it up.",
  "The Storm IV Twin-Pod cloud car was a model of cloud car manufactured by Bespin Motors, and used by the Bespin Wing Guard to patrol the skies surrounding the Cloud City colony and resort on Bespin.",
  "Sail barges were a class of large atmospheric transport. The Hutt crime lord Jabba Desilijic Tiure owned a modified LO-KD57 sail barge, the Khetanna, manufactured by Ubrikkian Industries, which he used to travel to the Great Pit of Carkoon."
]